/*
 * Do not edit this file.  It was automatically generated
 * by "rgb2c" from the file "Texture/metallic.rgb".
 *
 *   Size: 32 x 1
 *   Number of channels: 4
 *   Number of bits per texel: 16 (G_IM_SIZ_16b)
 *   Format of texel: G_IM_FMT_RGBA
 *
 * Example usage:
 *
 *   gsDPPipeSync (),
 *   gsDPSetCombineMode (G_CC_DECALRGB, G_CC_DECALRGB),
 *   gsDPSetTexturePersp (G_TP_PERSP),
 *   gsDPSetTextureLOD (G_TL_TILE),
 *   gsDPSetTextureFilter (G_TF_BILERP),
 *   gsDPSetTextureConvert(G_TC_FILT),
 *   gsDPSetTextureLUT (G_TT_NONE),
 *   gsDPLoadTextureBlock (tex_metallic, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 1, 0,
 *     G_TX_WRAP | G_TX_NOMIRROR, G_TX_WRAP | G_TX_NOMIRROR,
 *     G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
 */

#if 0	/* Image preview */
	+--------------------------------+
	|,,,......,,,,,,,~~~~~+++~~%~~~~~|
	+--------------------------------+
#endif

#ifdef __MWERKS__
#pragma align(16)
#else
static Gfx tex_metallic_C_dummy_aligner1[] = { gsSPEndDisplayList() };
#endif

unsigned short tex_metallic[] = {
	0x9001, 0x8001, 0x7001, 0x1085, 0x6001, 0x5001, 0x4001, 0x5001, 0x6001, 0x7001, 0x8001, 0x9001, 0x9005, 0x9009, 0x900d, 0x9011, 0x9211, 0x9215, 0x9219, 0x921d, 0x9221, 0x9225, 0x9229, 0x922d, 0x5211, 0x5215, 0xeeef, 0x5211, 0x4211, 0x4211, 0x4211, 0x4211, 
};

