/*
 * playseq.h
 */

#define	STACKSIZE	0x8000

#ifdef _LANGUAGE_C

#define MAX_BUFFER_LENGTH 1024
#define DMA_QUEUE_SIZE    50
#define AUDIO_HEAP_SIZE   500000
#define MAX_CLIST_SIZE    5000
#define MAX_AUDIO_LENGTH  4096
#define NUM_FIELDS        1
#define MAX_SEQ_LENGTH    50000

#define MAX_UPDATES     128
#define EVT_COUNT       128
#define MAX_VOICES      32
#define OUTPUT_RATE     32000

/*
 * Symbol generated by "makerom" to indicate the end of the code segment
 * in virtual (and physical) memory
 */
extern u8 _codeSegmentEnd[];

/*
 * Symbols generated by "makerom" to tell us where the segments are
 * in ROM.
 */
extern u8 _seqSegmentRomStart[],       _seqSegmentRomEnd[];
extern u8 _midibankSegmentRomStart[],  _midibankSegmentRomEnd[];
extern u8 _miditableSegmentRomStart[], _miditableSegmentRomEnd[];

#endif













