/*  Object Display Lists  */
/*  Automatically Generated File  */

#include "obj_texs.h"

#include "obj_verts.h"



Gfx obj0_dl[] = {
gsDPLoadTextureBlock(obj0_face0_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[0]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face1_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[3]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face2_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[6]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face3_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[9]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face4_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[12]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face5_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[15]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face6_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[18]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face7_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[21]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face8_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[24]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face9_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[27]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face10_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[30]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face11_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[33]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face12_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[36]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face13_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[39]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face14_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[42]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face15_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[45]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face16_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[48]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face17_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[51]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face18_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[54]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face19_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[57]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face20_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[60]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face21_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[63]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face22_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[66]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face23_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[69]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face24_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[72]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face25_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[75]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face26_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[78]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face27_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[81]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face28_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[84]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face29_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[87]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face30_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[90]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face31_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[93]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face32_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[96]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face33_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[99]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face34_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[102]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face35_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[105]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face36_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[108]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face37_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[111]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face38_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[114]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face39_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[117]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face40_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[120]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face41_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[123]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face42_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[126]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face43_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[129]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face44_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[132]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face45_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[135]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face46_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[138]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face47_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[141]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face48_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[144]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face49_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[147]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face50_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[150]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face51_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[153]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face52_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[156]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face53_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[159]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face54_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[162]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face55_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[165]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face56_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[168]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face57_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[171]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face58_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[174]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face59_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[177]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face60_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[180]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face61_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[183]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face62_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[186]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face63_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[189]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face64_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[192]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face65_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[195]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face66_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[198]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face67_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[201]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face68_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[204]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face69_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[207]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face70_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[210]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face71_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[213]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face72_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[216]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face73_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[219]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face74_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[222]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face75_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[225]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face76_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[228]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face77_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[231]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face78_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[234]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face79_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[237]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face80_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[240]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face81_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[243]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face82_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[246]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face83_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[249]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face84_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[252]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face85_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[255]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face86_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[258]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face87_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[261]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face88_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[264]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face89_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[267]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face90_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[270]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face91_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[273]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face92_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[276]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face93_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[279]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face94_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[282]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face95_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[285]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face96_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[288]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face97_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[291]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face98_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[294]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face99_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[297]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face100_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[300]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face101_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[303]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face102_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[306]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face103_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[309]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face104_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[312]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face105_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[315]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face106_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[318]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face107_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[321]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face108_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[324]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face109_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[327]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face110_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[330]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face111_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[333]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face112_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[336]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face113_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[339]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face114_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[342]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face115_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[345]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face116_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[348]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face117_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[351]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face118_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[354]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face119_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[357]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face120_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[360]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face121_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[363]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face122_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[366]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face123_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[369]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face124_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[372]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face125_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[375]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face126_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[378]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face127_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[381]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face128_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[384]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face129_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[387]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face130_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[390]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face131_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[393]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face132_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[396]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face133_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[399]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face134_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[402]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face135_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[405]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face136_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[408]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face137_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[411]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face138_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[414]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face139_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[417]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face140_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[420]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face141_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[423]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face142_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[426]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face143_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[429]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face144_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[432]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face145_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[435]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face146_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[438]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face147_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[441]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face148_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[444]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face149_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[447]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face150_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[450]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face151_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[453]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face152_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[456]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face153_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[459]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face154_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[462]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face155_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[465]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face156_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[468]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face157_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[471]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face158_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[474]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face159_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[477]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face160_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[480]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face161_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[483]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face162_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[486]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face163_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[489]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face164_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[492]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face165_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[495]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face166_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[498]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face167_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[501]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face168_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[504]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face169_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[507]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face170_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[510]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face171_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[513]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face172_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[516]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face173_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[519]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face174_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[522]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face175_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[525]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face176_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[528]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face177_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[531]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face178_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[534]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face179_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[537]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face180_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[540]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face181_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[543]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face182_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[546]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face183_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[549]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face184_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[552]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face185_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[555]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face186_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[558]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face187_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[561]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face188_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[564]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face189_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[567]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face190_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[570]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face191_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[573]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face192_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[576]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face193_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[579]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face194_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[582]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face195_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[585]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face196_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[588]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face197_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[591]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face198_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[594]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face199_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[597]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face200_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[600]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face201_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[603]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face202_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[606]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face203_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[609]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face204_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[612]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face205_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[615]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face206_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[618]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face207_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[621]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face208_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[624]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face209_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[627]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face210_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[630]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face211_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[633]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face212_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[636]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face213_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[639]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face214_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[642]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face215_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[645]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face216_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[648]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face217_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[651]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face218_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[654]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face219_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[657]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face220_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[660]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face221_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[663]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face222_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[666]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face223_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[669]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face224_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[672]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face225_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[675]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face226_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[678]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face227_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[681]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face228_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[684]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face229_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[687]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face230_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[690]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face231_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[693]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face232_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[696]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face233_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[699]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face234_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[702]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face235_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[705]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face236_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[708]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face237_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[711]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face238_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[714]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsDPLoadTextureBlock(obj0_face239_tex, G_IM_FMT_CI, G_IM_SIZ_8b, OBJ_SMAX, OBJ_TMAX, 0,
			G_TX_CLAMP, G_TX_CLAMP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
	gsDPLoadSync(),
	gsSPVertex(&(obj0_verts[717]), 3, 0),
	gsSP1Triangle(0, 1, 2, 0),
	gsDPPipeSync(),
gsSPEndDisplayList()
};

