/*
 * Do not edit this file.  It was automatically generated
 * by "rgb2c" from the file "Textures/terrain1.rgb".
 *
 *   Size: 32 x 1
 *   Number of channels: 4
 *   Number of bits per texel: 16 (G_IM_SIZ_16b)
 *   Format of texel: G_IM_FMT_RGBA
 *
 * Example usage:
 *
 *   gsSPTexture (128, 128, 0, G_TX_RENDERTILE, 1),
 *   gsDPPipeSync (),
 *   gsDPSetCombineMode (G_CC_MODULATERGBA, G_CC_MODULATERGBA),
 *   gsDPSetTexturePersp (G_TP_PERSP),
 *   gsDPSetTextureDetail (G_TD_CLAMP),
 *   gsDPSetTextureLOD (G_TL_TILE),
 *   gsDPSetTextureLUT (G_TT_NONE),
 *   gsDPSetTextureFilter (G_TF_BILERP),
 *   gsDPSetTextureConvert(G_TC_FILT),
 *   gsDPLoadTextureBlock (tex_metallic, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 1, 0
 *     G_TX_WRAP | G_TX_NOMIRROR, G_TX_WRAP | G_TX_NOMIRROR,
 *     G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
 */

#if 0	/* Image preview */
	+--------------------------------+
	|+,~~......,**++++~~~++~~+~+oo*oo|
	+--------------------------------+
#endif

static Gfx tex_metallic_C_dummy_aligner1[] = { gsSPEndDisplayList() };

unsigned short tex_metallic[] = {
0x9001,
0x8001,
0x7001,
0x1085,
0x6001,
0x5001,
0x4001,
0x5001,
0x6001,
0x7001,
0x8001,
0x9001,
0x9005,
0x9009,
0x900d,
0x9011,

0x9211,
0x9215,
0x9219,
0x921d,
0x9221,
0x9225,
0x9229,
0x922d,
0x5211,
0x5215,
0xeeef,
0x5211,
0x4211,
0x4211,
0x4211,
0x4211,
};

/*
0x4181,
0x41c1,
0x4181,
0x41c1,
0x41c1,
0x4201,
0x4201,
0x41c1,
0x4181,
0x4201,
0x4241,
0x4201,
0x4205,
0x4209,
0x420d,
0x4211,

0x4211,
0x4215,
0x4219,
0x421d,
0x4221,
0x4225,
0x4229,
0x422d,
0x4231,
0x4235,
0xeeef,
0x423d,
0x423f,
0x423f,
0x423f,
0x423f,
*/

